// eslint-disable-next-line no-unused-vars
/* global systemDictionary:true */
"use strict";

systemDictionary = {
	"huum-sauna adapter settings": {
		"en": "Adapter settings for huum-sauna",
		"de": "Adaptereinstellungen für huum-sauna",
		"ru": "Настройки адаптера для huum-sauna",
		"pt": "Configurações do adaptador para huum-sauna",
		"nl": "Adapterinstellingen voor huum-sauna",
		"fr": "Paramètres d'adaptateur pour huum-sauna",
		"it": "Impostazioni dell'adattatore per huum-sauna",
		"es": "Ajustes del adaptador para huum-sauna",
		"pl": "Ustawienia adaptera dla huum-sauna",
		"zh-cn": "huum-sauna的适配器设置"
	},
	"user": {
		"en": "Username",
		"de": "Benutzername",
		"ru": "Опция 1",
		"pt": "Opção 1",
		"nl": "Optie 1",
		"fr": "Option 1",
		"it": "opzione 1",
		"es": "Opción 1",
		"pl": "opcja 1",
		"zh-cn": "选项1"
	},
	"password": {
		"en": "Passwort",
		"de": "Kennwort",
		"ru": "Пароль",
		"pt": "Senha",
		"nl": "wachtwoord",
		"fr": "Mot de passe",
		"it": "Password",
		"es": "Contraseña",
		"pl": "Hasło",
		"zh-cn": "密码"
	},
	"refresh": {
		"en": "Refresh rate",
		"de": "Aktualisierungsrate",
		"ru": "Частота обновления",
		"pt": "Taxa de atualização",
		"nl": "Vernieuwingsfrequentie",
		"fr": "Fréquence de rafraîchissement",
		"it": "Frequenza di aggiornamento",
		"es": "Frecuencia de actualización",
		"pl": "Częstotliwość odświeżania",
		"zh-cn": "刷新率"
	},
	"refreshhelper": {
		"en": "In Seconds - Refresh rate for retrieving data from HUUM device in seconds",
		"de": "In Sekunden - Aktualisierungsrate zum Abrufen von Daten vom HUUM-Gerät in Sekunden",
		"ru": "Частота обновления для получения данных с устройства HUUM в секундах",
		"pt": "Taxa de atualização para recuperar dados do dispositivo HUUM em segundos",
		"nl": "Vernieuwingsfrequentie voor het binnen enkele seconden ophalen van gegevens van het HUUM-apparaat",
		"fr": "Taux de rafraîchissement pour récupérer les données de l'appareil HUUM en quelques secondes",
		"it": "Frequenza di aggiornamento per il recupero dei dati dal dispositivo HUUM in pochi secondi",
		"es": "Frecuencia de actualización para recuperar datos del dispositivo HUUM en segundos",
		"pl": "Częstotliwość odświeżania do pobierania danych z urządzenia HUUM w kilka sekund",
		"zh-cn": "以秒为单位从 HUUM 设备检索数据的刷新率"
	},
	"sleep": {
		"en": "Sleep Refresh Rate",
		"de": "Aktualisierungsrate",
		"ru": "Частота обновления",
		"pt": "Taxa de atualização",
		"nl": "Vernieuwingsfrequentie",
		"fr": "Fréquence de rafraîchissement",
		"it": "Frequenza di aggiornamento",
		"es": "Frecuencia de actualización",
		"pl": "Częstotliwość odświeżania",
		"zh-cn": "刷新率"
	},
	"sleephelper": {
		"en": "In Minutes - Sleep Refresh for Sauna Standby Mode to reduce thte traffic, 0 no traffic",
		"de": "In Minuten - Sleep Refresh für den Sauna-Standby-Modus, um den Traffic zu reduzieren, Wert = 0 kein lesen",
		"ru": "В минутах - обновление сна для режима ожидания сауны, чтобы уменьшить трафик, 0 нет трафика",
		"pt": "Em minutos - Atualização do sono para o modo de espera da sauna para reduzir o tráfego, 0 sem tráfego",
		"nl": "In minuten - Slaapvernieuwing voor sauna-standby-modus om het verkeer te verminderen, 0 geen verkeer",
		"fr": "En quelques minutes - Actualisation du sommeil pour le mode veille du sauna pour réduire le trafic, 0 pas de trafic",
		"it": "In pochi minuti - Ripristino del sonno per la modalità standby della sauna per ridurre il traffico, 0 nessun traffico",
		"es": "En minutos: actualización del sueño para el modo de espera de sauna para reducir el tráfico, 0 sin tráfico",
		"pl": "W minutach — odświeżanie snu w trybie czuwania w saunie w celu zmniejszenia ruchu, 0 brak ruchu",
		"zh-cn": "几分钟内 - 桑拿待机模式的睡眠刷新以减少流量，0 无流量"
	},
	"lightpath": {
		"en": "Path to state for light switching",
		"de": "Pfad zum Zustand für Lichtschaltung",
		"ru": "Путь к состоянию для переключения света",
		"pt": "Caminho para o estado para comutação de luz",
		"nl": "Pad naar status voor lichtschakeling",
		"fr": "Chemin d'accès à l'état pour la commutation de la lumière",
		"it": "Percorso verso lo stato per la commutazione della luce",
		"es": "Camino al estado para el cambio de luz",
		"pl": "Ścieżka do stanu przełączania światła",
		"zh-cn": "灯切换的状态路径"
	},
	"astrolight": {
		"en": "Use Astro",
		"de": "Astro Funktion nutzen",
		"ru": "Автоматическое включение света с помощью переключателя сауны с астрономическим временем",
		"pt": "Acender a luz automaticamente com interruptor sauna com tempos astro",
		"nl": "Schakel het licht automatisch in met schakelaar sauna met astrotijden",
		"fr": "Allumer la lumière automatiquement avec interrupteur sauna avec horaires astro",
		"it": "Accensione automatica della luce con interruttore sauna con orari astronomici",
		"es": "Encienda la luz automáticamente con el interruptor de sauna con tiempos astronómicos",
		"pl": "Automatyczne włączanie światła za pomocą przełącznika sauny z czasami astro",
		"zh-cn": "使用带有天文时代的开关桑拿自动打开灯"
	},
	"astrohelper": {
		"en": "Switch On light automatically using astro times!",
		"de": "Licht automatisch einschalten wenn es dunkel wird",
		"ru": "Автоматическое включение света с помощью переключателя сауны с астрономическим временем",
		"pt": "Acender a luz automaticamente com interruptor sauna com tempos astro",
		"nl": "Schakel het licht automatisch in met schakelaar sauna met astrotijden",
		"fr": "Allumer la lumière automatiquement avec interrupteur sauna avec horaires astro",
		"it": "Accensione automatica della luce con interruttore sauna con orari astronomici",
		"es": "Encienda la luz automáticamente con el interruptor de sauna con tiempos astronómicos",
		"pl": "Automatyczne włączanie światła za pomocą przełącznika sauny z czasami astro",
		"zh-cn": "使用带有天文时代的开关桑拿自动打开灯"
	},
	"setTargetTemperature": {
		"en": "Target Temperatur",
		"de": "Zieltemperatur",
		"ru": "Цель Temperatur",
		"pt": "Alvo Temperatur",
		"nl": "Target Temperatur",
		"fr": "Température cible",
		"it": "Obiettivo Temperatur",
		"es": "Meta Temperatur",
		"pl": "Target Temperatur",
		"zh-cn": "目标图表"
	},
	"setTargetHumidity": {
		"en": "Target Humidity",
		"de": "Zielfeuchtigkeit",
		"ru": "Целевая влажность",
		"pt": "Humidade de alvo",
		"nl": "Doel Humid",
		"fr": "Humidité cible",
		"it": "Obiettivo Umidità",
		"es": "Humedad de destino",
		"pl": "Target Humid",
		"zh-cn": "目标H"
	},
	"SteamPreset": {
		"en": "Preset for steam sauna mode",
		"de": "Voreinstellung für Dampfsauna Modus",
		"ru": "Пресет для режима паровой сауны",
		"pt": "Predefinição para o modo sauna a vapor",
		"nl": "Preset voor stoomsauna mode",
		"fr": "Prédéfini pour le mode sauna vapeur",
		"it": "Preimpostare la modalità sauna a vapore",
		"es": "Modo de sauna de vapor",
		"pl": "Preset for steam sauna mode",
		"zh-cn": "A. 动植物群的爆发"
	},
	"DryPreset": {
		"en": "Preset for dry sauna mode",
		"de": "Voreinstellung für Trockensauna",
		"ru": "Пресет для сухого сауны",
		"pt": "Predefinição para modo de sauna seca",
		"nl": "Preset voor droge sauna mode",
		"fr": "Prédéfini pour le mode sauna sec",
		"it": "Preimpostare la modalità sauna asciutta",
		"es": "Soporte para el modo de sauna seca",
		"pl": "Preset for dry sauna mode",
		"zh-cn": "干枯竭模式的爆发"
	},
	"steamPresetHumidityhelper": {
		"en": "Humidity Value for the Steam Sauna Mode",
		"de": "Feuchtigkeitswert für den Dampfsauna-Modus",
		"ru": "Влажность Значение для режима Steam Sauna",
		"pt": "Valor de umidade para o Modo Sauna Steam",
		"nl": "Humidity Value voor de Steam Sauna Mode",
		"fr": "Valeur d'humidité pour le mode Steam Sauna",
		"it": "Valore di umidità per la modalità sauna a vapore",
		"es": "Valor de humedad del modo Sauna de vapor",
		"pl": "Humidity Value for the Steam Sauna Mode (ang.)",
		"zh-cn": "Steam Sauna Mode"
	},
	"steamPresetTemphelper": {
		"en": "Temperature  Value for the Steam Sauna Mode",
		"de": "Temperaturwert für den Dampfsauna-Modus",
		"ru": "Температурная ценность для режима Steam Sauna",
		"pt": "Valor de Temperatura para o Modo Sauna Steam",
		"nl": "Temperatuur Value voor de Steam Sauna Mode",
		"fr": "Valeur de température pour le mode Steam Sauna",
		"it": "Valore di temperatura per la modalità sauna a vapore",
		"es": "Valor de temperatura para el modo Sauna de vapor",
		"pl": "Temperature Value for the Steam Sauna Mode (ang.)",
		"zh-cn": "对Steam Sauna Mode"
	},
	"dryPresetHumidityhelper": {
		"en": "Humidity Value for the Steam Sauna Mode",
		"de": "Feuchtigkeitswert für den Dampfsauna-Modus",
		"ru": "Влажность Значение для режима Steam Sauna",
		"pt": "Valor de umidade para o Modo Sauna Steam",
		"nl": "Humidity Value voor de Steam Sauna Mode",
		"fr": "Valeur d'humidité pour le mode Steam Sauna",
		"it": "Valore di umidità per la modalità sauna a vapore",
		"es": "Valor de humedad del modo Sauna de vapor",
		"pl": "Humidity Value for the Steam Sauna Mode (ang.)",
		"zh-cn": "Steam Sauna Mode"
	},
	"dryPresetTemphelper": {
		"en": "Temperature  Value for the Steam Sauna Mode",
		"de": "Temperaturwert für den Dampfsauna-Modus",
		"ru": "Температурная ценность для режима Steam Sauna",
		"pt": "Valor de Temperatura para o Modo Sauna Steam",
		"nl": "Temperatuur Value voor de Steam Sauna Mode",
		"fr": "Valeur de température pour le mode Steam Sauna",
		"it": "Valore di temperatura per la modalità sauna a vapore",
		"es": "Valor de temperatura para el modo Sauna de vapor",
		"pl": "Temperature Value for the Steam Sauna Mode (ang.)",
		"zh-cn": "对Steam Sauna Mode"
	},
	"tempReachedOffset": {
		"en": "temperature reached offset",
		"de": "temperatur erreicht offset",
		"ru": "температура достигла компенсации",
		"pt": "temperatura alcançada",
		"nl": "de temperatuur bereikte",
		"fr": "température atteinte",
		"it": "temperatura raggiunta offset",
		"es": "temperatura alcanzada",
		"pl": "temperatura sięgała",
		"uk": "температура досягається",
		"zh-cn": "温度抵消"
	  },
	"tempReachedOffsethelper": {
		"en": "offset for the intelligent sauna mode to lower the target temperature by the given value",
		"de": "offset für den intelligenten saunamodus, um die zieltemperatur um den vorgegebenen wert zu senken",
		"ru": "компенсация для интеллектуального режима сауны, чтобы снизить целевую температуру по данному значению",
		"pt": "offset para o modo de sauna inteligente para diminuir a temperatura do alvo pelo valor dado",
		"nl": "vertaling:",
		"fr": "compensation pour le mode intelligent de sauna pour réduire la température cible par la valeur donnée",
		"it": "offset per la modalità sauna intelligente per abbassare la temperatura di destinazione dal valore indicato",
		"es": "offset para el modo de sauna inteligente para reducir la temperatura de destino por el valor dado",
		"pl": "uwaga dla inteligentnego trybu sauna w celu obniżenia temperatury celowej przez daną wartość",
		"uk": "зміщення для розумного режиму сауни для зниження температури цілі за даним значенням",
		"zh-cn": "低目标温度的利害攸关者模式被特定价值抵消"
	}
};